export const SET_DARK_MODE = 'SET_DARK_MODE';

export const SIGN_IN_GOOGLE_AUTH = 'SIGN_IN_GOOGLE_AUTH';
export const SIGN_OUT_GOOGLE_AUTH = 'SIGN_OUT_GOOGLE_AUTH';

export const SET_IMPORTED_RECIPE = 'SET_IMPORTED_RECIPE';
export const REMOVE_IMPORTED_RECIPE = 'REMOVE_IMPORTED_RECIPE';

export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';