export const SET_DARK_MODE = 'SET_DARK_MODE';

export const SIGN_IN_GOOGLE_AUTH = 'SIGN_IN_GOOGLE_AUTH';
export const SIGN_OUT_GOOGLE_AUTH = 'SIGN_OUT_GOOGLE_AUTH';

export const SET_IMPORTED_RECIPE = 'SET_IMPORTED_RECIPE';
export const REMOVE_IMPORTED_RECIPE = 'REMOVE_IMPORTED_RECIPE';

export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

export const SET_RECIPE_VIEW_MODE = 'SET_RECIPE_VIEW_MODE';
export const SET_RECIPE_BOOK_VIEW_MODE = 'SET_RECIPE_BOOK_VIEW_MODE';

export const SET_RECIPES = 'SET_RECIPES';
export const SET_USER_RECIPE_IDS = 'SET_USER_RECIPE_IDS';

export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';
export const UNSET_REDIRECT_URL = 'UNSET_REDIRECT_URL';